### ISSUE TITLE
"Third Screen (type.fragment, external)" does not open on Zero Screen

### ISSUE THREAD

**Issue by Zhuinden** [open-turo/nibel#3]
This might not even be a bug,

However, `Third Screen (type.fragment, external)` shows message `ThirdScreenDetination should be ImplementationType.Fragment` in a toast message.

![Screenshot_20230727-213402](https://github.com/open-turo/nibel/assets/11718392/1b377fe0-af92-4edc-a468-875adb8b774c)

**Comment by Morfly** [comment]
That's correct. `Nibel.newFragmentEntry` will return `null` for screens with `ImplementationType.Composable`, since no fragment is generated in this case.
But I'll make the default type of a ThirdScreen to be `ImplementationType.Fragment` to avoid confusion. Thanks for raising this.

**Comment by Morfly** [comment]
I just updated the app, so that `ThirdScreen` now uses `ImplementationType.Fragment`. Now the error toast should be gone and the proper navigation is performed instead.

**Comment by Morfly** [comment]
I just updated the app, so that `ThirdScreen` now uses `ImplementationType.Fragment`. Now the error toast should be gone and the proper navigation is performed instead.
